version: "3"
services:
  #Nginx load balancer
  nginx:
    image: nginx:alpine
    container_name: production_nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 8080:8080

    #App container
  aspnetapp:
    image: aspnetapp
    build: .
    ports:
      - "8001:80"
